# Generated by Django 3.2 on 2021-05-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=100)),
                ('systems', models.IntegerField()),
                ('monm', models.CharField(max_length=100)),
                ('mone', models.CharField(max_length=100)),
                ('tuem', models.CharField(max_length=100)),
                ('tuee', models.CharField(max_length=100)),
                ('wedm', models.CharField(max_length=100)),
                ('wede', models.CharField(max_length=100)),
                ('thum', models.CharField(max_length=100)),
                ('thue', models.CharField(max_length=100)),
                ('frim', models.CharField(max_length=100)),
                ('frie', models.CharField(max_length=100)),
                ('satm', models.CharField(max_length=100)),
                ('sate', models.CharField(max_length=100)),
            ],
        ),
    ]
